test = read.table("household_power_consumption.txt", header = TRUE, sep = ";", colClasses = c("character", "character", rep("numeric", 7)), na.strings="?")
test$Date = as.Date(test$Date, format = "%d/%m/%Y")
project1 = subset(test, Date == "2007-02-01" | Date == "2007-02-02")
project1$DT = strptime(paste(project1$Date, project1$Time), "%Y-%m-%d %H:%M:%S")
png(file = "plot3.png")
plot(project1$DT, project1$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
points(project1$DT, project1$Sub_metering_2, type = "l", col = "red")
points(project1$DT, project1$Sub_metering_3, type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black", "red", "blue"))
dev.off()